### ISSUE TITLE
bit start receives an error and stops whenever a file is updated

### ISSUE THREAD

**Issue by felipeHerreraDell** [teambit/bit-angular#23]
Hello,

In my environment, I am able to run bit start successfully. However, when I update any file in the project, instead of an active reload, bit throws an error and stops.

error:
![bit_start_error](https://user-images.githubusercontent.com/90787886/133477095-ec62a1eb-ca7d-4e41-8469-042dfc95a1aa.png)

`uncaughtException [Error: EPERM: operation not permitted, lstat 'C:\Users\felie_herrera\Workspace\cloud-framework-components\testimony-angular-component\nod_modules\@dell\cloud_data_ops.components.testimony-card\dist\bundles\CY.TMP']
  errno: -4048,
  code: 'EPERM',
  syscall: 'lstat',
  path: 'C:\\Users\\felipe_herrera\\Workspace\\cloud-framework-components\\tesimony-angular-component\\node_modules\\@dell\\cloud_data_ops.components.testimny-card\\dist\\bundles\\CY.TMP'
}
`

bit version: 0.0.508
teambit.angular/angular-v12@0.0.30

I am using visual studio code and already tried updating a file with it closed by just using notepad but the error still occurred

**Comment by ocombe** [comment]
That should be fixed now. Let me know if that's not the case.
