### ISSUE TITLE
Bit build fails due to compilation issues

### ISSUE THREAD

**Issue by IdoMor** [teambit/bit-angular#28]
After executing all steps indicated in the readme file, executing bit build fails on the following error:
 Entry point of type library 'node' specified in compilerOptions
 
![image](https://user-images.githubusercontent.com/22292278/144218220-62eb84a6-1de8-4e95-9938-09c22b994be8.png)

environment:
node: v12.14.1
npm: 6.13.x
bit version: 0.0.577
bvm version:  0.0.30

**Comment by IdoMor** [comment]
repreduce also in npm version 8.1.4

**Comment by ocombe** [comment]
Are you trying to use `npm` to install dependencies ? you should always use `bit install`

**Comment by IdoMor** [comment]
mope.
folloed the instructions step by step

**Comment by ocombe** [comment]
does it work if you do `bit install @types/node` ?

**Comment by IdoMor** [comment]
yes!
We should add this as a default when the package is installed

**Comment by ocombe** [comment]
yes, I'll do it, thanks for the report
