### ISSUE TITLE
bit build fails for lack of typescriot

### ISSUE THREAD

**Issue by IdoMor** [teambit/bit-angular#30]
When executing bit built ot bit tag, the following error occur:

![image](https://user-images.githubusercontent.com/22292278/144997530-d0088dfe-522e-477d-a4bd-4b5d426275c9.png)

I had tried the following without any luck:
bit install typecript
bit install -u typecript
bit link typecript

bit version: 0.0.577
Angular CLI: 12.2.13
Node: 14.18.2
Package Manager: npm 6.14.15

**Comment by johnjspiteri** [comment]
@IdoMor did you figure this out?

**Comment by ocombe** [comment]
this should be solved in the latest versions, isn't it? Can you give me a repro @johnjspiteri ?

**Comment by johnjspiteri** [comment]
@ocombe, was just checking if he needed any help... or to close the issue.

Thank you 👍

**Comment by ocombe** [comment]
ok, closing it for now, we'll see if it's still a bug or not but I don't think so
