### ISSUE TITLE
Error on loading basic button after following steps from documentation

### ISSUE THREAD

**Issue by rishikeshjadhav** [teambit/bit-angular#31]
Getting below error when running command: bit start

![image](https://user-images.githubusercontent.com/17293029/148507882-777159dd-f1b0-4880-9447-7e38e5236bcc.png)

**Comment by rishikeshjadhav** [comment]
@ocombe @debs-obrien

**Comment by ocombe** [comment]
I can reproduce, looking at it, thanks

**Comment by rishikeshjadhav** [comment]
Adding more details as below,
bvm version: **0.0.30**
bit version: **0.0.595**
Angular version: **angular-v13@0.0.6**

Below are the workspace .jsonc contents:

/**
 * this is the main configuration file of your bit workspace.
 * for full documentation, please see: https://harmony-docs.bit.dev/workspace/configurations
 **/ {
  "$schema": "https://static.bit.dev/teambit/schemas/schema.json",
  /**
   * main configuration of the Bit workspace.
   **/
  "teambit.workspace/workspace": {
    /**
     * the name of the component workspace. used for development purposes.
     **/
    "name": "my-workspace-name",
    /**
     * set the icon to be shown on the Bit server.
     **/
    "icon": "https://static.bit.dev/bit-logo.svg",
    /**
     * default directory to place a component during `bit import` and `bit create`.
     * the following placeholders are available:
     * name - component name includes namespace, e.g. 'ui/button'.
     * scopeId - full scope-id includes the owner, e.g. 'teambit.compilation'.
     * scope - scope name only, e.g. 'compilation'.
     * owner - owner name in bit.dev, e.g. 'teambit'.
     **/
    "defaultDirectory": "{scope}/{name}",
    /**
     * default scope for all components in workspace.
     **/
    "defaultScope": "my-scope"
  },
  /**
   * main configuration for component dependency resolution.
   **/
  "teambit.dependencies/dependency-resolver": {
    /**
     * choose the package manager for Bit to use. you can choose between 'yarn', 'pnpm'
     */
    "packageManager": "teambit.dependencies/pnpm",
    "policy": {
      "dependencies": {},
      "peerDependencies": {}
    }
  },
  "teambit.angular/angular-v13@0.0.6": {},
  "teambit.workspace/variants": {
    "*": {
      "teambit.angular/angular-v13@0.0.6": {}
    }
  },
  "teambit.generator/generator": {
    "aspects": [
      "teambit.angular/angular-v13"
    ]
  }
}

**Comment by ocombe** [comment]
I know the cause of the bug, you can use `"teambit.angular/angular-v13@0.0.5"` in the mean time until I release a new version with a fix

**Comment by rishikeshjadhav** [comment]
@ocombe  Thank you for quick response on this. It worked with "teambit.angular/angular-v13@0.0.5". Looking forward for the fix.

**Comment by ocombe** [comment]
v0.0.7 has been released with the fix, thanks for the report !

**Comment by rishikeshjadhav** [comment]
@ocombe  That's awesome!

I have validated with v0.0.7 and it works fine. Thanks again for such quick turnaround on this.
