### ISSUE TITLE
Update readme to add teambit.angular dependency

### ISSUE THREAD

**Issue by ashishkrtewari** [teambit/bit-angular#36]
### What is the Issue

The readme does not recommend users to add the teambit.angular dependency which results in compilation errors.

Suggested Solution

Add 
```jsonc
"teambit.dependencies/dependency-resolver": {
    /**
     * choose the package manager for Bit to use. you can choose between 'yarn', 'pnpm'
     */
    "packageManager": "teambit.dependencies/pnpm",
    "policy": {
      "dependencies": {
        "@teambit/angular-v13": "0.0.19"
      },
      "peerDependencies": {}
    },
    "nodeLinker": "hoisted"
  },
```

to the workspace.jsonc example in readme

**Comment by ocombe** [comment]
You only need the env as a dependency if you use a custom env, and there will be a new bit command to define an env that will take care of the config for you, so hopefully that should be moot 🙂

**Comment by ashishkrtewari** [comment]
@ocombe 
If I just follow the exact steps mentioned in the readme, I face the following error 

![image](https://user-images.githubusercontent.com/10690564/153138763-0b815399-a7b1-4740-b2d0-23e54fd4dad5.png)

on running
```bash
bit start
```

Are you able to replicate it?

**Comment by ocombe** [comment]
No, are you using a custom env ?

**Comment by ashishkrtewari** [comment]
I found what I was doing wrong, 
I missed adding
```jsonc
"teambit.angular/angular-v13@x.x.x": {},
```

Shouldn't this be added by default in the workspace, along with
```jsonc
"teambit.workspace/variants": {
    "*": {
      "teambit.angular/angular-v13@0.0.19": {}
    }
  },
  "teambit.angular/angular-v13@0.0.19": {},
  "teambit.generator/generator": {
    "aspects": [
      "teambit.angular/angular-v13@0.0.19"
    ]
  }
```

**Comment by ocombe** [comment]
You are totally right, it should be added by default but there's a bug in the workspace generator, I'm fixing it, thanks !

**Comment by ocombe** [comment]
Actually I just checked and it's added by default.
It's even in the code that you copy pasted just above:
![image](https://user-images.githubusercontent.com/265378/153209109-d7125936-a5c8-4399-bdaf-1d26bb1d8239.png)

**Comment by ashishkrtewari** [comment]
Let me check then what was the issue again.
