### ISSUE TITLE
Module not found: Error: Can't resolve 'html-loader'

### ISSUE THREAD

**Issue by abhi9bakshi** [teambit/bit-angular#39]
I followed the steps in [https://github.com/teambit/bit-angular](https://github.com/teambit/bit-angular) as is and got the error on running `bit start` after creating `ui/my-button`. Running `bit start` directly after `bit new ng-workspace` doesn't throw error.

`Module not found: Error: Can't resolve 'html-loader' in '/home/abhi9/Library/Caches/Bit/capsules/4449ca0ffbd1bf94b513919b0aa94c2a37e76f6e/teambit.angular_angular@0.0.55/preview'`

![Error](https://user-images.githubusercontent.com/16088879/155285193-d53dc586-4803-466c-a6d0-8cae825a028f.png)

![HTML Loader](https://user-images.githubusercontent.com/16088879/155285235-15017719-e05f-428d-ba43-a1e427ec5da0.png)

![Missing library](https://user-images.githubusercontent.com/16088879/155285252-fd8a14a8-d71a-4fe0-af46-6952fad9d272.png)

OS: Zorin 16 (Ubuntu 20 based)
Node: 16.14.0

**Comment by AntGrisha** [comment]
same issue with node v12.22 and angular v10

**Comment by AntGrisha** [comment]
@abhi9bakshi I've fixed it by doing the following steps:
1. Clear cache created by `bit`, I mean this folder in your case `/home/abhi9/Library/Caches/Bit/capsules/4449ca0ffbd1bf94b513919b0aa94c2a37e76f6e`
2. update your peer deps in `workplace.jsonrc`:
`
      "peerDependencies": { ... ,
        "html-loader": "1.3.2",
        "remark-loader": "2.0.0"
      }
`
3. run `bit install`
4. run `bit start`

Issue has been resolved in my case

**Comment by abhi9bakshi** [comment]
Works like a charm, thanks :)
