### ISSUE TITLE
Cannot build/tag dependent components with v13

### ISSUE THREAD

**Issue by staizen-frankie** [teambit/bit-angular#53]
Hello, there seems to be an issue with tagging when there is multiple components that depends on each other in the same workspace.

## Envrionment:
```
  bit version   : 0.0.867
  node version  : v16.16.0
  npm version   : 6.14.17
  yarn version  : 1.22.19
  angular: teambit.angular/angular@1.2.17
```

## Steps to reproduce:
- use `bit create ng-module card`
- use `bit create ng-module profile`
- import card component into profile
  ```
  import { NgModule } from '@angular/core';
  import { CardModule } from '@ng-frankie/test-ng-v13.card';
  import { ProfileComponent } from './profile.component';

  @NgModule({
    declarations: [
      ProfileComponent
    ],
    imports: [
      CardModule
    ],
    exports: [
      ProfileComponent
    ]
  })
  export class ProfileModule {}

  ```
- bit tag/build failed with FatalDiagnosticError on profile component

## Error:
![Screenshot 2022-10-21 at 4 51 37 PM](https://user-images.githubusercontent.com/69791170/197155536-43ad6b05-7c37-495d-bfa3-baadc37fe5e5.png)

**Comment by ocombe** [comment]
Hello, this should be resolved with the last version (1.2.18), let me know if you still have the issue.
