### ISSUE TITLE
Update custom-env example

### ISSUE THREAD

**Issue by AntGrisha** [teambit/bit-angular#54]
Current implementation uses angular v12, though it is deprecated, according to the [docs](https://bit.dev/docs/angular-env/angular-versions).
Could you please update the example?

**Comment by ocombe** [comment]
yes I need to remove that one, but you can look here: https://github.com/teambit/bit-angular/tree/master/scopes/forks
or you can simply use the `ng-env` template to generate a custom env which will be based on the angular version that you want. This will use the default latest env (v15 for now):
```sh
bit create ng-env envs/my-angular-env --env teambit.angular/angular
```

But if you want v14 for example, you can do that:
```
bit create ng-env envs/my-angular-env --env teambit.angular/versions/angular-v14
```
